config/routes.rb
Rails.application.routes.draw do
  resources :bar_tabs
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :flares
  resources :games do
    collection do
      patch :submit_picks, :action => :submit_picks
    end
  end
  resources :game_states
  resources :points
  resources :rosters do
    resources :drafts
  end
  resources :picks
  resources :challenges
  resources :fights
  resources :fighters, shallow: true do 
    get 'fighter_info', to: 'fighters#fighter_info'
  end
  resources :events
  resources :invites
  resources :seasons
  devise_for :users, :controllers => { :registrations => "users/registrations" }
  resources :users
  resources :leagues 
  resources :memberships
  
  root 'static_pages#home'

  get 'static_pages/home'

  get 'about', to: 'static_pages#about'
  get 'terms', to: 'static_pages#terms'
  get 'rules', to: 'static_pages#rules'

  get 'static_pages/help'

end

app/views/shared/_back_to_profile.erb
<% unless request.original_url == root_url %>
<div class="row" id="back-to-profile">
  <div class="col-xs-12">
    <div id="back-to-profile-link">
      <%= link_to "<-- Back to Profile", root_url %>
    </div>
  </div>
</div> 
<% end %>

app/views/shared/_challenges_slider.html.erb
<!-- Challenge Slider -->
<!--
<div class="row events-view">
<ul class="nav nav-pills nav-justified head-challenge-tabs">
  <li><a data-toggle="pill" href="#previous-tab">Previous</a></li>
  <li class="active"><a data-toggle="pill" href="#current-tab">Current</a></li>
  <li><a data-toggle="pill" href="#upcoming-tab">UpComing</a></li>
</ul>
</div>
-->
<!--
<div class="tab-content">
  -->
  <!-- start the previous tab -->
    <%# render "shared/challenge_tabs/previous_games" %>   
  <!-- end the previous tab -->
  <!-- start the Current Tab -->
  <%= render "shared/challenge_tabs/current_game" %>
  <!-- ends the current Tab -->
  <!-- start the Upcoming events -->
  
    <%# render "shared/challenge_tabs/upcoming_games" %>  

  <!-- ends the UpComing events -->

<!--
</div> 
-->
<!-- ends the tabbed content -->

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert alert-back <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/shared/_game_buttons.html.erb
<% if event.games.where(user_id: @user.id) == [] %> 
	<%= link_to "new game", new_game_path(event_id: event.id), class: "btn btn-primary" %> <br>
<% else %>
	<%= link_to "edit game", edit_game_path(event.games.where(user_id: @user.id).last), class: "btn btn-primary" %> <br>    
<% end %>

app/views/shared/_leagues_slider.html.erb
<div class="row">
	<div class="col-xs-12">
		<div class="col-xs-12 leagues-header">
			<h1 class="title">Leagues</h1>
			<i type="button" class="fa fa-info-circle tips" data-toggle="tooltip" data-placement="bottom" title="Join a league and challenge friends."></i>
			<%= link_to "Find League", leagues_path, :class => "btn btn-primary btn-responsive pull-right", title: "Find your tribe. Click here to find a league, or create your own.", onclick: "userVisitsLeagues();" %></div>
	</div>
</div>
<% if @user.leagues == [] %>
	<div class="no-leagues">
		<p>You are not currently in a league. <br>
		Join a league to: </p>
		<ul>
			<li>Challenge friends</li> 
			<li>Draft Fighters and build a team. <em>(Coming Soon!)</em></li>
			<li>Earn more points.</li>
			<li>Earn more coins.</li>
		</ul>
		<p>Best of all, <em>It's free.</em><i class="fa fa-smile-o"></i><br>
		- The Cage Machine</p>
	</div>
<% else %>
<div id="leagues-slider" class="carousel" data-ride="carousel" data-interval="false">
<% if @user.leagues.offset(1) != [] %>
  		<div class="row slide-control">
  				<a class="left carousel-control" href="#leagues-slider" role="button" data-slide="prev"><span class="fa fa-angle-left"></span></a>
  				<a class="right carousel-control" href="#leagues-slider" role="button" data-slide="next">
  					<span class="fa fa-angle-right"></span>
  				</a>
  		</div>

  <% end %>
		<div class="carousel-inner" role="listbox">
		<% @user.leagues.each_with_index do |league, index| %>
		<% if index == 0 %>
			<div class="item active"><!-- first league -->
		<% else %> 
			<div class="item"><!-- other leagues --> 
		<% end %> 
			<div class="row league-header">
				<div class="col-sm-6">
				<%= image_tag league.flare.image, class: "profile-pic" %>
				<%= link_to("League Name: #{league.name}", league_path(league.id)) %>
					<p>	<%= league.kind %>: <%= league.season_name %> <br>
						Start: <%= league.season_start %> <br>
						Finish: <%= league.season_end %></p>
				</div>
				<div class="col-sm-6">
					<div id="league-action-1" class="action-area hidden-xs">
					<%= link_to 'Visit League', league_path(league), class: "btn btn-primary btn-responsive pull-right", title: "Visit this league. Challenge other league members. Draft Fighters (coming soon).", onclick: "userVisitsLeague();"  %> 
					<%= link_to 'Draft Fighters', new_roster_path(league_id: league.id, membership_id: league.memberships.find_by(user_id: current_user.id)), class: "btn btn-success disabled btn-responsive pull-right", alert: "Draft Feature coming soon!", title: 'Draft Feature coming soon!'%> <br>
					</div>
					<div id="league-action-2" class="action-area visible-xs-inline pull-right">
					<%= link_to 'Draft Fighters', new_roster_path(league_id: league.id, membership_id: league.memberships.find_by(user_id: current_user.id)), class: "btn btn-success disabled btn-responsive", alert: "Draft Feature coming soon!", title: 'Draft Feature coming soon!'%>
					<%= link_to 'Visit League', league_path(league), class: "btn btn-primary btn-responsive", title: "Visit this league. Challenge other league members. Draft Fighters (coming soon).", onclick: "userVisitsLeague();"  %> 
					</div>
				</div>
			</div>
			<div class="row league-leaders">
			<div class="col-sm-12">
				<div class="col-sm-6">
				<% 	@leaderboard = league.memberships.sort_by(&:season_points_sort).reverse[0..5]
					@leaderboard[0...3].each.with_index do |member, index| %>
						<% if index == 0 %>		
							<div class="league-leader">
								<div class="rank">
									<i class="fa fa-trophy" data-toggle="tooltip" data-placement="right" title="<%= member.points_till_champion(current_user, league) %>" onclick="userClicksTrophy();"></i>
								</div>
								<div class="league-leader-flare">
									<% unless member.user.fighter == nil %>
										<%= image_tag member.user.fighter.image, class: "img-league-member hidden-xs" %>
									<% else %> 
										<%= image_tag "placeholder.png", class: "img-league-member hidden-xs" %>
									<% end %>
								</div>
								<div class="league-leader-name"><%= link_to member.user.username, user_path(member.user.id), onclick: "userWantsToBeChampAndVisitsChamp();" %></div>
								<div class="league-leader-season-points"><%= member.season_points(member) %></div>
								<div class="clearfix"></div>
							</div>
						<% else %> 
							<div class="league-leader">
								<div class="rank"><%= index %></div>
								<div class="league-leader-flare">
									<% unless member.user.fighter == nil %>
										<%= image_tag member.user.fighter.image, class: "img-league-member hidden-xs" %>
									<% else %> 
										<%= image_tag "placeholder.png", class: "img-league-member hidden-xs" %>
									<% end %>
								</div>
								<div class="league-leader-name"><%= link_to member.user.username, user_path(member.user.id) %></div>
								<div class="league-leader-season-points"><%= member.season_points(member) %></div>
								<div class="clearfix"></div>
							</div>
						<% end %> 
					<% end %>
				</div>
				<div class="col-sm-6 second-tier-leaders">
				<% @leaderboard[3..5].to_a.each.with_index do |member, index| %>
				<div class="league-leader">
					<div class="rank"><%= index + 3 %></div>
					<div class="league-leader-flare">
						<% unless member.user.fighter == nil %>
							<%= image_tag member.user.fighter.image, class: "img-league-member hidden-xs" %>
						<% else %> 
							<%= image_tag "placeholder.png", class: "img-league-member hidden-xs" %>
						<% end %>
					</div>
					<div class="league-leader-name"><%= link_to member.user.username, user_path(member.user.id) %></div>
					<div class="league-leader-season-points"><%= member.season_points(member) %></div>
					<div class="clearfix"></div>
				</div>
				<% end %>
					
				</div>
			</div>
			</div>
			<div class="row" id="league-footer">
				<div class="col-xs-12">
					<%= link_to 'Visit League to see all Players and Make Challenges -->', league_path(league.id), class: "pull-right" %>

				</div>
			</div>
	
			</div><!-- end item/item active --> 
<% end %>
</div><!-- Carousel inner -->


</div><!-- end Leagues slider -->
<% end %> <!-- Ends the else statement on the if no leagues logic -->

app/views/shared/_user_header.html.erb
<div class="col-xs-12 user-header">
	<div class="col-xs-4 col-sm-7">
		<% if current_user == @user %>
			<% unless @user.fighter == nil %>
				<%= link_to image_tag(@user.fighter.image, class: "profile-pic"), edit_user_registration_path, onclick: "userClicksUserSettings();" %> 
			<% else %>
				<%= link_to image_tag("placeholder.png", class: "profile-pic"), edit_user_registration_path, onclick: "userClicksUserSettings();" %>
			<% end %>
		<% else %>
			<% unless @user.fighter == nil %>
				<%= image_tag @user.fighter.image, class: "profile-pic" %> 
			<% else %>
				<%= image_tag "placeholder.png" %>
			<% end %>
		<% end %>

		<div class="hidden-xs" id="user-info">
			<p>Name: <%= @user.username %></p>
		</div>
	</div>
	<div class="col-xs-8 col-sm-5">
			<p class="visible-xs-block text-left">Name: <%= @user.username %></p>

		<% if @user == current_user %> 
				<%= link_to 'Edit Settings', edit_user_registration_path, class: "btn btn-default pull-right" , onclick: "userClicksUserSettings();" %><i type="button" class="fa fa-info-circle pull-right tips" data-toggle="tooltip" data-placement="bottom" title="Change your profile picture, password, and username."></i>
		<% end %>
	</div>
</div>
<div class="clearfix"></div>
<div class="col-xs-12" id="user-points">
	<div class="col-sm-3"> </div>
	<div class="col-sm-9 col-xs-12">
		<div class="col-xs-6 col-sm-4">
		<i type="button" class="fa fa-info-circle tips" data-toggle="tooltip" data-placement="bottom" title="Belt rank symbolizes your on the app rank"></i>
			<p><%= @user.user_level %>
			<br><small><%= @user.points %> Points</small><br>

			</p>
		</div>
		<div class="col-xs-6 col-sm-4">
		<i type="button" class="fa fa-info-circle tips" data-toggle="tooltip" data-placement="bottom" title="Cage Coins help you buy things. Challenge your friends with Cage Coins."></i>
			<p>Cage Coins <br>
				<small><%= @user.coins %> coins</small>
			</p>
		</div>
		<div class="col-xs-12 col-sm-4">
			<i type="button" class="fa fa-info-circle tips" data-toggle="tooltip" data-placement="bottom" title="Badges are cool."></i>
			<% unless @badges == [] %>  
				<% @badges.each do |badge| %>
					<% if badge[0] == "Champ" %>						
						<a href="/leagues/<%= badge[1].id %>" data-toggle="tooltip" data-placement="top" title="Champion of <%= badge[1].name %>">
							<i class="medals medals-the_crown"></i>
						</a>
					<% elsif badge[0] == "1st" %>
						<a href="/leagues/<%= badge[1].id %>" data-toggle="tooltip" data-placement="top" title="1st runner-up of <%= badge[1].name %>"><i class="medals medals-gold_medal"></i></a>
					<% elsif badge[0] == "2nd" %> 
						<a href="/leagues/<%= badge[1].id %>" data-toggle="tooltip" data-placement="top" title="2nd runner-up of <%= badge[1].name %>"><i class="medals medals-silver_medal"></i></a>
					<% elsif badge[0] == "3rd" %> 
						<a href="/leagues/<%= badge[1].id %>" data-toggle="tooltip" data-placement="top" title="3rd runner-up of <%= badge[1].name %>"><i class="medals medals-bronze_medal"></i></a>
					<% end %>
				<% end %>
			<% else %> 
				<p>No Badges</p>
			<% end %> 
		</div>
	</div>
</div>