config/routes.rb
Rails.application.routes.draw do
  resources :bar_tabs
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :flares
  resources :games do
    collection do
      patch :submit_picks, :action => :submit_picks
    end
  end
  resources :game_states
  resources :points
  resources :rosters do
    resources :drafts
  end
  resources :picks
  resources :challenges
  resources :fights
  resources :fighters, shallow: true do 
    get 'fighter_info', to: 'fighters#fighter_info'
  end
  resources :events
  resources :invites
  resources :seasons
  devise_for :users, :controllers => { :registrations => "users/registrations" }
  resources :users
  resources :leagues 
  resources :memberships
  
  root 'static_pages#home'

  get 'static_pages/home'

  get 'about', to: 'static_pages#about'
  get 'terms', to: 'static_pages#terms'
  get 'rules', to: 'static_pages#rules'

  get 'static_pages/help'

end

app/views/shared/challenge_tabs/_previous_games.html.erb
<div id="previous-tab" class="tab-pane fade">
	  <div class="table-responsive leaderboard row">
	    <table class="table table-hover">
	      <thead>
	        <tr>
	          <th>Fight Night</th>
	          <th>Score</th>
	          <th>Actions</th>
	        </tr>
	      </thead>
	      <tbody>
	        <% @events.where(active: false, lock: true).each do |event| %>
	        <tr>
	          <td><%= event.title %></td>
	          <td><%= event.score(current_user) %></td>
	          <td><% unless event.games.find_by(user_id: current_user.id) == nil%><%= link_to "Show Game", game_path(event.games.find_by(user_id: current_user.id)), class: "btn btn-sm btn-primary" %><% end %></td>
	        </tr>
			<% end %>
	      </tbody>
	    </table>
	  </div>
    
</div>

app/views/shared/challenge_tabs/_upcoming_games.html.erb
<div id="upcoming-tab" class="tab-pane fade">

  <div class="table-responsive leaderboard row">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Fight Night</th>
          <th>Play</th>
        </tr>
      </thead>
      <tbody>
    
        <% @events.where(active: true).order(:start_time).drop(1).each do |event| %> 
          <tr>
            <td><%= event.title %><br><%= event.start_time.strftime("%A, %B %d, %Y") %></td>
            <td>
              <% if DateTime.now >= event.start_time - 4.hours && event.games.where(user_id: @user.id) != [] %>
                <%= link_to "Show Picks", game_path(event.games.where(user_id: @user.id).last), class: "btn-sm btn-primary" %>
              <% elsif DateTime.now >= event.start_time - 4.hours && event.games.where(user_id: @user.id) == [] %>
                <a class="btn btn-default">Event closed</a>
              <% elsif event.games.where(user_id: current_user.id) == [] %> 
                <%= link_to "Make Picks", new_game_path(event_id: event.id), class: "btn-sm btn-success" %> <br>
              <% else %>
                <% unless event.games.where(user_id: current_user.id).last == [] %> 
                <%= link_to "Change Picks", edit_game_path(event.games.where(user_id: current_user.id).last), class: "btn btn-danger" %> <br>
                <% end %> 
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

</div>