config/routes.rb
Rails.application.routes.draw do
  resources :bar_tabs
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :flares
  resources :games do
    collection do
      patch :submit_picks, :action => :submit_picks
    end
  end
  resources :game_states
  resources :points
  resources :rosters do
    resources :drafts
  end
  resources :picks
  resources :challenges
  resources :fights
  resources :fighters, shallow: true do 
    get 'fighter_info', to: 'fighters#fighter_info'
  end
  resources :events
  resources :invites
  resources :seasons
  devise_for :users, :controllers => { :registrations => "users/registrations" }
  resources :users
  resources :leagues 
  resources :memberships
  
  root 'static_pages#home'

  get 'static_pages/home'

  get 'about', to: 'static_pages#about'
  get 'terms', to: 'static_pages#terms'
  get 'rules', to: 'static_pages#rules'

  get 'static_pages/help'

end

app/models/draft.rb
class Draft < ActiveRecord::Base
  belongs_to :user
  belongs_to :fighter
  belongs_to :roster
  before_save :ensure_fighter_is_available, message: "Fighter has been taken"

  protected

  	def ensure_fighter_is_available
  		selected_fighter = self.fighter
  		league = self.roster.membership.league
  		league.memberships.each do |m|
  			m.rosters.each do |r|
  				r.drafts.each do |d|
  					if d.fighter = selected_fighter
  						false
  					end
  				end
  			end
  		end
  	end
end

app/controllers/drafts_controller.rb
class DraftsController < ApplicationController
  before_action :set_draft, only: [:show, :edit, :update, :destroy]

  # GET /drafts
  # GET /drafts.json
  def index
    @drafts = Draft.all
  end

  # GET /drafts/1
  # GET /drafts/1.json
  def show
  end

  # GET /drafts/new
  def new
    @draft = Draft.new
  end

  # GET /drafts/1/edit
  def edit
  end

  # POST /drafts
  # POST /drafts.json
  def create
    @draft = Draft.new(draft_params)

    respond_to do |format|
      if @draft.save
        format.html { redirect_to @draft, notice: 'Draft was successfully created.' }
        format.json { render :show, status: :created, location: @draft }
      else
        format.html { render :new }
        format.json { render json: @draft.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drafts/1
  # PATCH/PUT /drafts/1.json
  def update
    respond_to do |format|
      if @draft.update(draft_params)
        format.html { redirect_to @draft, notice: 'Draft was successfully updated.' }
        format.json { render :show, status: :ok, location: @draft }
      else
        format.html { render :edit }
        format.json { render json: @draft.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drafts/1
  # DELETE /drafts/1.json
  def destroy
    @draft.destroy
    respond_to do |format|
      format.html { redirect_to drafts_url, notice: 'Draft was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_draft
      @draft = Draft.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def draft_params
      params.require(:draft).permit(:event, :user_id, :fighter_1_id, :fighter_2_id, :fighter_3_id, :fighter_id, :roster_id)
    end
end

app/helpers/drafts_helper.rb
module DraftsHelper
end

app/views/drafts/_form.html.erb
<%= form_for(@draft) do |f| %>
  <% if @draft.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@draft.errors.count, "error") %> prohibited this draft from being saved:</h2>

      <ul>
      <% @draft.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event %><br>
    <%= f.text_field :event %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :fighter_1_id %><br>
    <%= f.number_field :fighter_1_id %>
  </div>
  <div class="field">
    <%= f.label :fighter_2_id %><br>
    <%= f.number_field :fighter_2_id %>
  </div>
  <div class="field">
    <%= f.label :fighter_3_id %><br>
    <%= f.number_field :fighter_3_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/drafts/edit.html.erb
<h1>Editing Draft</h1>

<%= render 'form' %>

<%= link_to 'Show', @draft %> |
<%= link_to 'Back', drafts_path %>

app/views/drafts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Drafts</h1>

<table>
  <thead>
    <tr>
      <th>Event</th>
      <th>User</th>
      <th>Fighter 1</th>
      <th>Fighter 2</th>
      <th>Fighter 3</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @drafts.each do |draft| %>
      <tr>
        <td><%= draft.event %></td>
        <td><%= draft.user %></td>
        <td><%= draft.fighter_1_id %></td>
        <td><%= draft.fighter_2_id %></td>
        <td><%= draft.fighter_3_id %></td>
        <td><%= link_to 'Show', draft %></td>
        <td><%= link_to 'Edit', edit_draft_path(draft) %></td>
        <td><%= link_to 'Destroy', draft, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Draft', new_draft_path %>

app/views/drafts/new.html.erb
<h1>New Draft</h1>

<%= render 'form' %>

<%= link_to 'Back', drafts_path %>

app/views/drafts/show.html.erb
<p>
  <strong>Event:</strong>
  <%= @draft.event %>
</p>

<p>
  <strong>User:</strong>
  <%= @draft.user %>
</p>

<p>
  <strong>Fighter 1:</strong>
  <%= @draft.fighter_1_id %>
</p>

<p>
  <strong>Fighter 2:</strong>
  <%= @draft.fighter_2_id %>
</p>

<p>
  <strong>Fighter 3:</strong>
  <%= @draft.fighter_3_id %>
</p>

<%= link_to 'Edit', edit_draft_path(@draft) %> |
<%= link_to 'Back', drafts_path %>