config/routes.rb
Rails.application.routes.draw do
  resources :bar_tabs
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :flares
  resources :games do
    collection do
      patch :submit_picks, :action => :submit_picks
    end
  end
  resources :game_states
  resources :points
  resources :rosters do
    resources :drafts
  end
  resources :picks
  resources :challenges
  resources :fights
  resources :fighters, shallow: true do 
    get 'fighter_info', to: 'fighters#fighter_info'
  end
  resources :events
  resources :invites
  resources :seasons
  devise_for :users, :controllers => { :registrations => "users/registrations" }
  resources :users
  resources :leagues 
  resources :memberships
  
  root 'static_pages#home'

  get 'static_pages/home'

  get 'about', to: 'static_pages#about'
  get 'terms', to: 'static_pages#terms'
  get 'rules', to: 'static_pages#rules'

  get 'static_pages/help'

end

app/models/flare.rb
class Flare < ActiveRecord::Base
	mount_uploader :image, ImageUploader 
	has_many :leagues

end

app/controllers/flares_controller.rb
class FlaresController < ApplicationController
  before_action :set_flare, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!


  # GET /flares
  # GET /flares.json
  def index
    @flares = Flare.all
  end

  # GET /flares/1
  # GET /flares/1.json
  def show
  end

  # GET /flares/new
  def new
    @flare = Flare.new
  end

  # GET /flares/1/edit
  def edit
  end

  # POST /flares
  # POST /flares.json
  def create
    @flare = Flare.new(flare_params)

    respond_to do |format|
      if @flare.save
        format.html { redirect_to @flare, notice: 'Flare was successfully created.' }
        format.json { render :show, status: :created, location: @flare }
      else
        format.html { render :new }
        format.json { render json: @flare.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flares/1
  # PATCH/PUT /flares/1.json
  def update
    respond_to do |format|
      if @flare.update(flare_params)
        format.html { redirect_to @flare, notice: 'Flare was successfully updated.' }
        format.json { render :show, status: :ok, location: @flare }
      else
        format.html { render :edit }
        format.json { render json: @flare.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flares/1
  # DELETE /flares/1.json
  def destroy
    @flare.destroy
    respond_to do |format|
      format.html { redirect_to flares_url, notice: 'Flare was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flare
      @flare = Flare.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flare_params
      params.require(:flare).permit(:title, :description, :image, :premium, :remote_image_url)
    end
end

app/helpers/flares_helper.rb
module FlaresHelper
end

app/views/flares/_form.html.erb
<%= form_for(@flare) do |f| %>
  <% if @flare.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flare.errors.count, "error") %> prohibited this flare from being saved:</h2>

      <ul>
      <% @flare.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :remote_image_url, "or image URL" %> <br>
    <%= f.text_field :remote_image_url %> 
  </div>
  <div class="field">
    <%= f.label :premium %><br>
    <%= f.check_box :premium %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/flares/edit.html.erb
<h1>Editing Flare</h1>

<%= render 'form' %>

<%= link_to 'Show', @flare %> |
<%= link_to 'Back', flares_path %>

app/views/flares/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Flares</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Image</th>
      <th>Premium</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flares.each do |flare| %>
      <tr>
        <td><%= flare.title %></td>
        <td><%= flare.description %></td>
        <td><%= flare.image %></td>
        <td><%= flare.premium %></td>
        <td><%= link_to 'Show', flare %></td>
        <td><%= link_to 'Edit', edit_flare_path(flare) %></td>
        <td><%= link_to 'Destroy', flare, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Flare', new_flare_path %>

app/views/flares/new.html.erb
<h1>New Flare</h1>

<%= render 'form' %>

<%= link_to 'Back', flares_path %>

app/views/flares/show.html.erb
<%= image_tag @flare.image_url(:profile).to_s, class: "profile-pic" %>
<p>
  <strong>Title:</strong>
  <%= @flare.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @flare.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= @flare.image %>
</p>

<p>
  <strong>Premium:</strong>
  <%= @flare.premium %>
</p>

<%= link_to 'Edit', edit_flare_path(@flare) %> |
<%= link_to 'Back', flares_path %>